title: Chess Compiler Learn
description: Chess blogs and tutorials
baseurl: "/learn"
url: "https://chesscompiler.github.io"
permalink: /:slug/
theme: null

plugins:
  - jekyll-sitemap

social:
  instagram: "chesscompiler"
  youtube: "chesscompiler"

# ğŸ“ Folders and files to include in the site output
include:          # <--- ADD THIS SECTION
  - "_layouts"
